### ISSUE TITLE
Cant run

### ISSUE THREAD

**Issue by MrDeadKingz** [ZackaryW/reldplayer#1]
hey Zackary, im looking to use this and expand on it, i was wondering if you could reach out and give me a hand with setup, discord: @mrdeadkingz

**Comment by ZackaryW** [comment]
hi there,
may i know what errors you run into?
currently, it's available in pypi as an alpha release and `pip install reldplayer[all]. It should be able to set up on all dependencies

**Comment by MrDeadKingz** [comment]
been trying to run it in pycharm, i just keep getting exit code 0's
